; PlatformIO Project Configuration File
; ESP8266 Fan Controller - NodeMCU V2

[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino
monitor_speed = 115200
upload_port = COM19
upload_speed = 115200
upload_resetmethod = nodemcu
lib_deps = 
	knolleary/PubSubClient@^2.8

; AP Mode Configuration
; SSID: Fan_Control
; Password: 12345678
; IP: 192.168.4.1
